# Generated by Django 2.2.5 on 2019-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20190927_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='course',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='session',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
