# Generated by Django 2.2.5 on 2019-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_auto_20191005_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
