# Generated by Django 2.2 on 2020-01-22 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_session_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
