# Generated by Django 2.2 on 2020-02-01 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0008_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='interested_tutors',
            field=models.ManyToManyField(related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
