# Generated by Django 2.2 on 2020-02-04 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200204_0213'),
        ('session', '0009_session_interested_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='interested_tutors',
            field=models.ManyToManyField(blank=True, related_name='interested_tutors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='session',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='session',
            name='time_slot',
            field=models.ManyToManyField(blank=True, to='common.Timeslot'),
        ),
    ]
