# Generated by Django 2.2 on 2020-02-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_auto_20200204_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time_slot',
        ),
    ]
