# Generated by Django 2.2 on 2020-02-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_remove_session_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='has_materials',
            field=models.BooleanField(default=False),
        ),
    ]
