# Generated by Django 2.2 on 2020-02-09 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0014_auto_20200209_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contract', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_contract',
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
