# Generated by Django 2.2 on 2020-02-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_sessioncontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncontract',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_contract', to='session.Session'),
            preserve_default=False,
        ),
    ]
