# Generated by Django 2.2 on 2020-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_remove_session_time_slot'),
        ('common', '0003_auto_20200204_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='owner',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.ManyToManyField(blank=True, to='session.Session'),
        ),
    ]
