# Generated by Django 2.2 on 2020-02-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_remove_session_time_slot'),
        ('common', '0004_auto_20200204_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='session',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
