# Generated by Django 2.2 on 2020-02-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200204_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
