# Generated by Django 2.2 on 2020-02-04 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200204_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='session',
        ),
    ]
