# Generated by Django 2.2 on 2020-02-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_timeslot_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
