# Generated by Django 2.2 on 2020-02-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200209_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsavailability',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_availability', to='session.Session'),
        ),
    ]
