# Generated by Django 2.2 on 2019-06-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('personal_statement', models.TextField(null=True)),
                ('hobbies', models.TextField(null=True)),
                ('transportation', models.PositiveIntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Public Transportation')])),
                ('send_more_students', models.BooleanField(default=False)),
                ('send_text', models.BooleanField(default=True)),
                ('max_distance', models.PositiveIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
