# Generated by Django 2.2 on 2020-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('tutor', 'Tutor'), ('student', 'Student')], default='staff', max_length=255),
        ),
    ]
