# Generated by Django 2.2 on 2020-02-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('tutor', 'tutor'), ('student', 'student')], default='staff', max_length=255),
        ),
    ]
