# Generated by Django 2.2 on 2020-02-17 23:43

from django.db import migrations


def create_thorough_relations(apps, schema_editor):
    UserProfile = apps.get_model('userprofile', 'UserProfile')
    RegisteredCourses = apps.get_model('userprofile', 'RegisteredCourses')
    for user_profile in UserProfile.objects.all():
        for course in user_profile.courses.all():
            RegisteredCourses(userprofile=user_profile, course=course).save()


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_registeredcourses'),
    ]

    operations = [
        migrations.RunPython(create_thorough_relations, reverse_code=migrations.RunPython.noop),
    ]
