# Generated by Django 2.2 on 2020-02-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200217_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
    ]
