# Generated by Django 2.2 on 2020-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('userprofile', '0008_remove_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(through='userprofile.RegisteredCourses', to='course.Course'),
        ),
    ]
