# Generated by Django 2.2 on 2020-02-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        ('userprofile', '0009_userprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='notification.NotificationPreference'),
        ),
    ]
