# Generated by Django 2.2 on 2020-02-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_userprofile_notification_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preference',
        ),
    ]
