# Generated by Django 2.2.4 on 2020-07-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_remove_userprofile_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_distance',
            field=models.PositiveIntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50')], default=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='transportation',
            field=models.PositiveIntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Public Transportation')], default=1),
        ),
    ]
