# Generated by Django 2.2.5 on 2019-10-13 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_auto_20191009_0612'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('schedule', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Schedule')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_bill', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
