# Generated by Django 2.2 on 2020-04-05 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 5, 19, 40, 10, 71701)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='extra_info',
            field=models.TextField(null=True),
        ),
    ]
