# Generated by Django 2.2 on 2020-04-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200405_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='student',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tutor',
        ),
    ]
