# Generated by Django 2.2 on 2020-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200405_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
