# Generated by Django 2.2 on 2020-01-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191009_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
