# Generated by Django 2.2 on 2020-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
