# Generated by Django 2.2 on 2020-04-05 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_is_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 18, 46, 16, 553793, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
